# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_topic_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='parent_posts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_posts', to='forum.Post'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='viewed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
