# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 07:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20170731_0705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='parent',
        ),
    ]
