# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_remove_post_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
        migrations.AddField(
            model_name='post',
            name='score',
            field=models.SmallIntegerField(default=0),
        ),
    ]
