# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20170801_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'created', 'ordering': ['-created']},
        ),
    ]
