# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20170728_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(),
        ),
    ]
