# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_remove_post_report_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='report_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
